version: '3.8'

services:
  db:
    hostname: db
    container_name: db
    image: gvenzl/oracle-xe:11-slim
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 1234
    volumes:
      - oracle-data:/opt/oracle/oradata

  spring-app:
    container_name: spring-app
    build: ./spring-app
    image: spring-app
    ports:
      - "18080:18080"
    volumes:
      - ./spring-app:/usr/local/app

  react-app:
    container_name: react-app
    build: ./react-app
    image: react-app
    ports:
      - "80:80"
    volumes:
      - ./react-app:/app 

volumes:
  oracle-data:
    driver: local
