version: '3.8'

services:
  oracle-db:
    container_name: oracle-db
    image: gvenzl/oracle-xe:11-slim
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/1234@localhost:1521/xe"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    environment:
      ORACLE_PASSWORD: 1234
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network

  spring-app:
    container_name: spring-app
    build: ./spring-app
    image: spring-app
    ports:
      - "18080:18080"
    volumes:
      - ./spring-app:/usr/local/app
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: on-failure:3
    command: >
      sh -c "sleep 60"
    networks:
      - app-network

  react-app:
    container_name: react-app
    build: ./react-app
    image: react-app
    ports:
      - "80:80"
    volumes:
      - ./react-app:/app
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
  
volumes:
  oracle-data:
    driver: local
