version: '3.8'

services:
  oracle-db:
    container_name: oracle-db
    image: gvenzl/oracle-xe:11-slim
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 1234
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network

  spring-app:
    container_name: spring-app
    build: ./spring-app
    ports:
      - "18080:18080"
    volumes:
      - ./spring-app:/usr/local/app
    depends_on:
      oracle-db
    restart: on-failure
    networks:
      - app-network

  react-app:
    container_name: react-app
    build: ./react-app
    image: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
  
volumes:
  oracle-data:
    driver: local
