server:
  port: ${PORT}
  address: ${ADDRESS}

spring:
  data:
    postgresql:
      username: ${DATA_POSTGRES_USERNAME}
      password: ${DATA_POSTGRES_PASSWORD}
      authentication-database: ${DATA_POSTGRES_AUTHENTICATION_DB}
      database: ${DATA_POSTGRES_DB}
      uri: ${DATA_POSTGRES_URI}
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG