server:
  port: ${PORT}
  address: ${ADDRESS}

spring:
  datasource:
    url: ${DATA_POSTGRES_URI}
    username: ${DATA_POSTGRES_USERNAME}
    password: ${DATA_POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

authentication:
  server:
    url: ${AUTHENTICATION_SERVER_URL}