# Base image
FROM openjdk:17-jdk-slim

# 기본 포트 설정
EXPOSE 18080

# JAR 파일 복사
COPY ./build/libs/co-working-0.0.1-SNAPSHOT.jar /usr/local/app/co-working-0.0.1-SNAPSHOT.jar

# 작업 디렉터리 설정
WORKDIR /usr/local/app

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "/usr/local/app/co-working-0.0.1-SNAPSHOT.jar"]