server:
  port: ${PORT}
  address: ${ADDRESS}

spring:
  datasource:
    url: ${DATA_POSTGRES_URI}
    username: ${DATA_POSTGRES_USERNAME}
    password: ${DATA_POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

file:
  upload-dir: ${FILE_UPLOAD_DIR}