spring:
  datasource:
    url: ${ENV_DB:jdbc:oracle:thin:@192.168.219.143:1521:xe}?oracle.jdbc.timezoneAsRegion=false
    username: ${ENV_USERNAME:brobro332}
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    kr.co.co_working: debug

jwt:
  secret-key: awghf23G@R%@4t4kqwlg4tQ$@##Q%q43gjlqarbhjgbq3ghq43r%@qtqgagwghjglhqq23r23